# Generated by Django 4.0.6 on 2022-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pcreated_on_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.img', upload_to='img'),
        ),
    ]
